name: release
on:
  workflow_dispatch:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set env variables
      uses: ./pearl/g/github/env/
    - run: sudo apt-get update
    - run: sudo apt-get install autopoint
    - run: sudo apt-get install lzop
    - run: sudo apt-get install libgmp-dev libmpfr-dev libmpc-dev
    - run: sudo apt-get install libipc-run-perl libfile-slurp-perl
    - run: sudo apt-get install qemu-user qemu-user-static binfmt-support
    - run: sudo apt-get install qemu-system
    - run: sudo apt-get install sharutils
    - run: sudo apt-get install gettext
    - run: sudo apt-get install xz-utils
    - run: sudo apt-get install device-tree-compiler
    - run: sudo apt-get install libtool-bin
    - run: git submodule update --init pearl
    - run: make -C pearl -j13 build/released/pipcet/pearl-toolchain/toolchain.tar.zstd
    - run: tar -C pearl -xf build/released/pipcet/pearl-toolchain/toolchain.tar.zstd
    - run: make -C pearl -j13 bootloaders/barebox/barebox{checkout}
    - run: make -C pearl -j13 bootloaders/grub/grub{checkout}
    - run: make -C pearl -j13 bootloaders/m1n1/m1n1{checkout}
    - run: make -C pearl -j13 bootloaders/u-boot/u-boot{checkout}
    - run: make -C pearl -j13 build/bootloaders.tar.zstd{release}
    - run: make -C pearl -j13 {release}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
